apiVersion: v1
kind: Service
metadata:
  name: {{ include "clients.fullname" . }}
  labels:
    {{- include "clients.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 8081
      protocol: TCP
  selector:
    app: clients
